=== chnpmy/webTech/homework/9/cookbook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
        xmlns:xs =  "http://www.w3.org/2001/XMLSchema"
        targetNamespace = "http://162.105.146.180:8106/homework/9/cookbook"
        xmlns = "http://162.105.146.180:8106/homework/9/cookbook"
        elementFormDefault = "qualified">
    <xs:element name = "cookbook">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="recipe" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "name"
                                        type =  "xs:string"
                                        minOccurs = "1"
                                        maxOccurs = "1"/>
                            <xs:element name = "ingredient" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name"
                                                    type="xs:string"
                                                    minOccurs="1"
                                                    maxOccurs="1"/>
                                        <xs:element name="amount"
                                                    type="xs:string"
                                                    minOccurs="1"
                                                    maxOccurs="1"/>
                                        <xs:element name="unit"
                                                    type="xs:string"
                                                    minOccurs="0"
                                                    maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name = "cooking">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="step"
                                                    type="xs:string"
                                                    minOccurs="1"
                                                    maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name = "tips">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name = "tip"
                                                    type =  "xs:string"
                                                    minOccurs = "1"
                                                    maxOccurs = "unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== chnpmy/webTech/homework/9/cook.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="cookbook.xsl"?>
<cookbook
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://162.105.146.180:8106/homework/9/cookbook cookbook.xsd">
    <recipe>
        <name>木须肉</name>
        <ingredient>
            <name>猪脊肉</name>
            <amount>200</amount>
            <unit>g</unit>
        </ingredient>
        <ingredient>
            <name>黄瓜</name>
            <amount>100</amount>
            <unit>g</unit>
        </ingredient>
        <ingredient>
            <name>鸡蛋</name>
            <amount>2</amount>
            <unit>个</unit>
        </ingredient>
        <ingredient>
            <name>油</name>
            <amount>适量</amount>
        </ingredient>
        <ingredient>
            <name>盐</name>
            <amount>适量</amount>
        </ingredient>
        <ingredient>
            <name>木耳</name>
            <amount>适量</amount>
        </ingredient>
        <ingredient>
            <name>黄花</name>
            <amount>适量</amount>
        </ingredient>
        <ingredient>
            <name>葱</name>
            <amount>适量</amount>
        </ingredient>
        <ingredient>
            <name>姜</name>
            <amount>适量</amount>
        </ingredient>
        <ingredient>
            <name>料酒</name>
            <amount>适量</amount>
        </ingredient>
        <ingredient>
            <name>水淀粉</name>
            <amount>适量</amount>
        </ingredient>
        <ingredient>
            <name>芝麻油</name>
            <amount>适量</amount>
        </ingredient>
        <ingredient>
            <name>生抽</name>
            <amount>适量</amount>
        </ingredient>
        <cooking>
            <step>准备食材</step>
            <step>猪脊肉切成片加一点蛋清、料酒、淀粉</step>
            <step>抓匀后腌渍二十分钟</step>
            <step>木耳与黄花温水泡发后反复冲洗干净</step>
            <step>木耳撕成小朵，黄花切去花蒂挤净水份备用</step>
            <step>黄瓜斜刀切成段</step>
            <step>黄瓜切面竖起，然后切成片</step>
            <step>鸡蛋打散，倒入油锅中炒散后盛出备用</step>
            <step>锅中留少许底油，加入葱姜末炒香</step>
            <step>加入肉片快速翻炒</step>
            <step>当肉片变白断生时，加入黄瓜片略炒</step>
            <step>加入黄花与木耳快速翻炒</step>
            <step>加入适量生抽</step>
            <step>加入炒好的鸡蛋</step>
            <step>加入适量盐调味</step>
            <step>用少许水淀粉勾芡</step>
            <step>关火后加芝麻油调味出锅</step>
        </cooking>
        <tips>
            <tip>木耳清洗时加盐搓会很容易清洗</tip>
            <tip>这是道快手菜，一定要大火快炒</tip>
        </tips>
    </recipe>
</cookbook>
